<script src="<?php echo e(url('backend')); ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/popper.js/dist/umd/popper.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/assets/js/main.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/jszip/dist/jszip.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/pdfmake/build/pdfmake.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/pdfmake/build/vfs_fonts.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/vendors/datatables.net-buttons/js/buttons.colVis.min.js"></script>
<script src="<?php echo e(url('backend')); ?>/assets/js/init-scripts/data-table/datatables-init.js"></script>
<?php /* /home/devtools/PHP/projects/tm-site/resources/views/partials/js.blade.php */ ?>